from pydantic import BaseModel, Field
from typing import List, Dict, Any, Optional

class ChatMessage(BaseModel):
    role: str = Field(..., description="The role of the message author, e.g., 'user' or 'assistant'.")
    content: str = Field(..., description="The textual content of the message.")

class ChatQueryRequest(BaseModel):
    message: str = Field(..., min_length=1, description="The natural language question or instruction from the user.")
    top_k: int = Field(default=4, ge=1, le=10, description="The maximum number of document chunks to retrieve as context.")
    conversation_history: Optional[List[ChatMessage]] = Field(
        default=None, 
        description="Optional list of preceding messages to maintain conversational memory."
    )

class CitationSource(BaseModel):
    filename: str = Field(..., description="The original name of the source document file.")
    document_id: str = Field(..., description="The unique UUID string assigned to the document.")
    chunk_index: int = Field(..., description="The zero-based sequential index of the text segment.")

class ChatQueryResponse(BaseModel):
    answer: str = Field(..., description="The context-aware semantic answer generated by the LLM.")
    sources: List[CitationSource] = Field(..., description="List of source document citations used to answer the query.")
