from pydantic import BaseModel, Field
from typing import List, Dict, Any

class RetrievedContext(BaseModel):
    text: str = Field(..., description="The matched chunk text block retrieved from the vector space.")
    document_id: str = Field(..., description="The parent tracking identification number.")
    filename: str = Field(..., description="The text source filename metadata property.")
    chunk_index: int = Field(..., description="The source section sorting sequence tracking context position.")
    score: float = Field(..., description="Calculated similarity confidence index or raw geometric distance metrics.")

class GenerationResult(BaseModel):
    answer: str = Field(..., description="The text payload generated by the foundational intelligence LLM model.")
    context_used: List[RetrievedContext] = Field(..., description="Chronological listing of source document context markers.")
    tokens_consumed: Optional[Dict[str, int]] = Field(default=None, description="Optional payload tracking precise execution usage.")
